using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Windows.Forms;

namespace DevServerControl
{
    public partial class HostFile : Form
    {
        public HostFile()
        {
            InitializeComponent();
        }

        private string _hostsContent;

        //_managedHosts format: (string)FQDN: (bool)pointing to localhost?
        private Dictionary<string, bool> _managedHosts = new Dictionary<string, bool>();

        private void HostFile_Load(object sender, EventArgs e)
        {
            //Load hosts file
            var hostsReader = new StreamReader("C:\\Windows\\System32\\drivers\\etc\\hosts");
            _hostsContent = hostsReader.ReadToEnd();
            hostsReader.Close();

            //Process with hosts
            foreach (var host in _hostsContent.Split('\n'))
            {
                if (host.EndsWith("\t#Managed-by-DevServerControl\r")) //We're managing the record only generated by us
                {
                    var hostSplit = host.Split('\t');
                    switch (hostSplit[0])
                    {
                        case "127.0.0.1": //handling IPv4
                            _managedHosts[hostSplit[1]] = true;
                            break;
                        case "::1": //handling IPv6
                            continue; //We're not handling IPv6 traffics at this moment
                        default:
                            _managedHosts[hostSplit[1]] = false;
                            break;
                    }
                }

                foreach (var manageHost in _managedHosts)
                {
                    Form1.AppendText(Form1.tbx_log, manageHost.Key + ": " + manageHost.Value, 10, Color.Black, false);//dev
                    //Append test to Form: HostFile
                    
                }
            }
        }
    }
}